import sys
import os
import json
import time
import traceback
from argparse import ArgumentParser
from dotenv import load_dotenv
import openai
from tqdm import tqdm

# Ensure src_VanilaRAG is in the path
sys.path.append('/home/student/ActiveRAG/src_VanilaRAG')

# Load environment variables from .env file
load_dotenv()

# Set OpenAI API key from environment variable
openai.api_key = os.getenv('API_KEY')


class VanillaRAGAgent:
    def __init__(self, model='gpt-4o-mini-2024-07-18'):
        self.message = []
        self.model = model

    def send_vanilla_rag_message(self, retrieved_passages, question):
        """
        Send a message to OpenAI API to generate a response based on retrieved passages.
        """
        message = {
            'role': 'user',
            'content': f"Use the following passages to answer the question.\n\nPassages:\n{retrieved_passages}\n\nQuestion: {question}"
        }
        self.message.append(message)

        try:
            ans = openai.ChatCompletion.create(
                model=self.model,
                messages=self.message,
                temperature=0.2,
                n=1
            )
            self.parse_message(ans)
            return ans
        except Exception as e:
            print(e)
            time.sleep(20)
            ans = openai.ChatCompletion.create(
                model=self.model,
                messages=self.message,
                temperature=0.2,
                n=1
            )
            self.parse_message(ans)
            return ans

    def parse_message(self, completion):
        content = completion['choices'][0]['message']['content']
        role = completion['choices'][0]['message']['role']
        record = {'role': role, 'content': content}
        self.message.append(record)
        return record

    def get_output(self):
        """
        Get the latest output generated by the model.
        """
        if len(self.message) == 0:
            raise ValueError("No messages found. Cannot get output.")
        return self.message[-1]['content']


class VanillaRAG:
    def __init__(self, agent: VanillaRAGAgent, retriever):
        self.agent = agent
        self.retriever = retriever

    def retrieve_passages(self, query: str, top_k: int = 5):
        """
        Retrieve relevant passages for the input query.
        """
        return self.retriever(query, top_k)

    def run(self, question: str, top_k: int = 5):
        """
        Run the VanillaRAG model: retrieve passages and generate an answer.
        """
        # Step 1: Retrieve relevant passages
        passages = self.retrieve_passages(question, top_k)
        
        # Combine retrieved passages into a single string
        retrieved_passages = "\n".join(passages)

        # Step 2: Send message to OpenAI to generate an answer
        self.agent.send_vanilla_rag_message(retrieved_passages, question)

        # Get and return the result
        return self.agent.get_output()


def run_vanilla_rag_experiment(question: str, retriever, top_k: int):
    """
    Run the VanillaRAG experiment with the provided question and retriever.
    """
    # Initialize the VanillaRAG agent
    vanilla_rag_agent = VanillaRAGAgent()

    # Set up the VanillaRAG with the agent and retriever
    vanilla_rag = VanillaRAG(vanilla_rag_agent, retriever)

    # Run the VanillaRAG model
    result = vanilla_rag.run(question, top_k)

    print(f"VanillaRAG Result: {result}")
    return result


def mock_retriever(query: str, top_k: int):
    """
    Mock retriever function to simulate passage retrieval.
    Replace this with actual retrieval logic (e.g., using a search engine, BM25, etc.).
    """
    return [f"Passage {i} related to {query}" for i in range(1, top_k + 1)]


if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('--dataset', required=True)
    parser.add_argument('--topk', type=int, required=True)
    args = parser.parse_args()

    dataset = args.dataset
    filename = f'data/data_{dataset}_sampled.jsonl'
    topk = args.topk

    vanillarag_directory = f'vanila/{dataset}/top{topk}/vanillarag'

    # Create directory for logs if it doesn't exist
    if not os.path.exists(vanillarag_directory):
        os.makedirs(vanillarag_directory)

    with open(filename, 'r', encoding='utf-8') as file:
        for i, line in tqdm(enumerate(file)):
            try:
                data = json.loads(line)
                question = data['question']

                # Run VanillaRAG Experiment using the mock retriever (replace with actual retriever)
                vanillarag_result = run_vanilla_rag_experiment(question, mock_retriever, topk)

                # Save the result
                with open(f'{vanillarag_directory}/{dataset}_idx_{i}.json', 'w', encoding='utf-8') as vr_file:
                    json.dump({'question': question, 'vanilla_rag_result': vanillarag_result}, vr_file)

            except Exception as e:
                current_time = time.strftime("%Y-%m-%d %H:%M:%S")
                print(f"Error at index {i} - {current_time}: {e}")
                traceback.print_exc()
                break
